### ISSUE TITLE
Avoid loading Ethereum-related vaults in DOM when Avalance is chosen

### ISSUE THREAD

**Issue by kargakis** [ribbon-finance/ribbon-frontend#311]
Currently, when the Avalance network is chosen, all the Ethereum vaults are briefly loaded in the UI and all related requests are made to node and graph APIs, before the page switches to the Avalance vault. This can be improved so unnecessary requests are avoided and the UX/page loading time is improved.

**Comment by fqlx** [comment]
We will investigate more. I think we hit a limitation of Metamask here - maybe I'm wrong.  Product wants us to load the vaults as a placeholder while Metamask is in an "undefined" or "unconnected" network state.  When the network state changes to Avalanche, we show the Avax vaults and hence those related API requests.  The issue seems to be Metmask is in an "undefined" state for ~500ms until it connects to the Avalanche network.

**Comment by kenchangh** [comment]
Solved this by having multiple open network providers
